# Generated by Django 4.1.7 on 2024-04-23 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff'), ('Customer', 'Customer'), ('Agent', 'Agent')], default='Customer', max_length=50, verbose_name='User Role')),
                ('profile_pic', models.ImageField(blank=True, upload_to='avatars/')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('id_type', models.CharField(choices=[('NRC', 'NRC'), ('Passport', 'Passport'), ('Lisense', 'Lisense')], max_length=50)),
                ('id_number', models.CharField(blank=True, max_length=300, verbose_name='identtity number')),
                ('location', models.CharField(blank=True, max_length=50, verbose_name='location')),
                ('id_front', models.ImageField(blank=True, null=True, upload_to='id_front/')),
                ('id_back', models.ImageField(blank=True, null=True, upload_to='id_back/')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('is_supervisor', models.BooleanField(default=False, verbose_name='staff')),
                ('is_manager', models.BooleanField(default=False, verbose_name='staff')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empolyee_number', models.BigIntegerField(blank=True, null=True)),
                ('balance', models.FloatField(null=True)),
                ('bank', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_acc', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_acc', models.CharField(blank=True, max_length=200, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_agent', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
