# Generated by Django 4.1.7 on 2024-04-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_clientprofile_pin_alter_clientprofile_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='pin',
            field=models.IntegerField(default=None),
        ),
    ]
