# Generated by Django 4.1.7 on 2024-05-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_clientprofile_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='gross_salary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='pin',
            field=models.IntegerField(default=1111),
        ),
    ]
