# Generated by Django 4.1.7 on 2024-04-23 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('loan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_payment_made', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Acctive'), ('closed', 'Closed'), ('bad debt', 'Bad debt')], default='active', max_length=100)),
                ('transaction_type', models.CharField(choices=[('Disbursement', 'Disbursement,'), ('Loan Repayment', 'Loan Repayment'), ('Penalty', 'Penalty'), ('bad debt', 'Bad Debt')], max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.clientprofile')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='loan.loan')),
            ],
        ),
        migrations.CreateModel(
            name='BadDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.FloatField()),
                ('debt_amount', models.FloatField()),
                ('settlement_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('loan_transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.loantransaction', verbose_name='Loan Transactions')),
            ],
        ),
    ]
