# Generated by Django 4.1.7 on 2024-04-23 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loantransaction',
            name='loan',
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='loan_obj',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='loan_obj', to='loan.loan'),
            preserve_default=False,
        ),
    ]
