# Generated by Django 4.1.7 on 2024-05-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_loantransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Disbursement', 'Disbursement,'), ('Loan Repayment', 'Loan Repayment'), ('Penalty', 'Penalty'), ('Bad Debt', 'Bad Debt')], max_length=255),
        ),
    ]
