# Generated by Django 4.1.7 on 2024-04-23 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('period', models.IntegerField(default=1, help_text='in months', null=True)),
                ('purpose', models.CharField(max_length=100)),
                ('total_interest', models.FloatField(null=True)),
                ('payable_amount', models.FloatField(null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('method_of_payment', models.CharField(choices=[('mobile', 'mobile'), ('bank account', 'Bank Account'), ('credit card', 'Credit Card'), ('debit card', 'Debit Card'), ('loan', 'Loan')], max_length=200, null=True)),
                ('loan_type', models.CharField(choices=[('civil servant loans', 'Civil Servant Loans'), ('famers loans', 'Famers Loans'), ('micro business loans', 'Micro Business Loans')], max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('closed', 'Closed')], default='pending', max_length=100, null=True)),
                ('approved_at_branch', models.CharField(blank=True, max_length=900, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='account.clientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_score', models.BigIntegerField(blank=True, null=True)),
                ('crb', models.BigIntegerField(blank=True, null=True)),
                ('number_of_loan', models.BigIntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='account.clientprofile')),
            ],
        ),
    ]
