# Generated by Django 4.1.7 on 2024-04-22 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('period', models.IntegerField(null=True)),
                ('purpose', models.CharField(max_length=100)),
                ('balance', models.FloatField(null=True)),
                ('monthly_interest', models.FloatField(null=True)),
                ('total_interest', models.FloatField(null=True)),
                ('monthly_repayment', models.FloatField(null=True)),
                ('total_repayment', models.FloatField(null=True)),
                ('start_date', models.DateField(auto_now_add=True, null=True)),
                ('due_date', models.DateField(auto_now=True, null=True)),
                ('end_date', models.DateField(auto_now_add=True, null=True)),
                ('method_of_payment', models.CharField(choices=[('mobile', 'mobile'), ('bank account', 'Bank Account'), ('credit card', 'Credit Card'), ('debit card', 'Debit Card'), ('loan', 'Loan')], max_length=200, null=True)),
                ('loan_type', models.CharField(choices=[('civil servant loans', 'Civil Servant Loans'), ('famers loans', 'Famers Loans'), ('micro business loans', 'Micro Business Loans')], max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('closed', 'Closed')], default='pending', max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='account.clientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_payment_made', models.BooleanField(default=True)),
                ('transaction_type', models.CharField(choices=[('Disbursement', 'Disbursement,'), ('Loan Repayment', 'Loan Repayment'), ('Penalty', 'Penalty'), ('bad debt', 'Bad debt')], max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='account.clientprofile')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='account.clientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LoanTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_payment_made', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Acctive'), ('closed', 'Closed'), ('bad debt', 'Bad debt')], default='active', max_length=100)),
                ('transaction_type', models.CharField(choices=[('Disbursement', 'Disbursement,'), ('Loan Repayment', 'Loan Repayment'), ('Penalty', 'Penalty'), ('bad debt', 'Bad Debt')], max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.clientprofile')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='loan.loan')),
            ],
        ),
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_score', models.BigIntegerField(blank=True, null=True)),
                ('crb', models.BigIntegerField(blank=True, null=True)),
                ('number_of_loan', models.BigIntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.clientprofile')),
            ],
        ),
    ]
