# Generated by Django 4.1.7 on 2024-09-27 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('interest_rate_method', models.CharField(choices=[('flate rate', 'Flate Rate'), ('reducing blanace', 'Reducing Balance'), ('interest only', 'Interest Only')], default='flate_rate', max_length=20)),
                ('duration_period', models.CharField(choices=[('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], default='months', max_length=20)),
                ('duration_length', models.IntegerField(null=True)),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('civil servant loans', 'Civil Servant Loans'), ('famers loans', 'Famers Loans'), ('micro business loans', 'Micro Business Loans'), ('collatral loans', 'Collatral Loans'), ('salary advance', 'Salary Advance')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='FlatRateProducts',
            fields=[
                ('loanproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loan.loanproduct')),
            ],
            bases=('loan.loanproduct',),
        ),
        migrations.CreateModel(
            name='InterestOnly',
            fields=[
                ('loanproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loan.loanproduct')),
            ],
            bases=('loan.loanproduct',),
        ),
        migrations.CreateModel(
            name='ReducingBalance',
            fields=[
                ('loanproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loan.loanproduct')),
            ],
            bases=('loan.loanproduct',),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='loan.loan'),
        ),
    ]
