# Generated by Django 4.1.7 on 2024-10-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loanproduct_alter_loan_loan_type_flatrateproducts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='duration_period',
            field=models.CharField(choices=[('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], max_length=20, null=True),
        ),
    ]
