# Generated by Django 4.1.7 on 2024-10-28 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_loanproduct_duration_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='loan.loan'),
        ),
    ]
