# Generated by Django 4.1.7 on 2024-10-28 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_alter_loanproduct_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='duration_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='loan.loan'),
        ),
    ]
