# Generated by Django 4.1.7 on 2024-11-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_alter_loanproduct_duration_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_rate_method',
            field=models.CharField(choices=[('flate rate', 'Flate Rate'), ('reducing blanace', 'Reducing Balance'), ('interest only', 'Interest Only')], default='Flate Rate', max_length=20),
        ),
    ]
