# Generated by Django 4.1.7 on 2024-11-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_alter_loanproduct_interest_rate_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_rate_method',
            field=models.CharField(choices=[('Flate Rate', 'Flate Rate'), ('Reducing Balance', 'Reducing Balance'), ('Interest Only', 'Interest Only')], default='Flate Rate', max_length=20),
        ),
    ]
