# Generated by Django 5.1.2 on 2024-12-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0007_alter_loanproduct_interest_rate_method"),
    ]

    operations = [
        # Alter fields
        migrations.AlterField(
            model_name="loan",
            name="loan_type",
            field=models.CharField(max_length=200, null=True),
        ),
        # Delete models
        migrations.DeleteModel(
            name="FlatRateProducts",
        ),
        migrations.DeleteModel(
            name="InterestOnly",
        ),
        migrations.DeleteModel(
            name="ReducingBalance",
        ),
    ]