# Generated by Django 5.1.2 on 2025-01-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0008_remove_interestonly_loanproduct_ptr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="balance",
            field=models.FloatField(null=True),
        ),
    ]
