from django.urls import path
from . import views

urlpatterns = [
    path('', views.LoginView, name='login'),
    path('staff', views.Dashboard, name='staff' ),
    path('clients',views.AllClients, name='clients'),
    path('client_details/<int:client_id>/', views.ClientDetails, name='client_details'),
    path('reports', views.Reports, name='reports'),
    path('loans', views.Loans, name='loans'),
    path('pending-loans', views.PendingLoansView, name='pending-loans'),
    path('create-client', views.CreatClient, name='create-client'),
    path('attach-client', views.AttachClient, name='attach-client'),
    path('created-client', views.CreateClientView, name='created-client'),
    path('client-attachement/<int:client_id>/', views.ClientAttachement, name='client-attachement'),
    path('create-loan', views.CreateLoan, name="create-loan"),
    path('pass-clientID/<int:client_id>/', views.passIDToAddLoan, name='pass-clientID'),
    path('get-loan-product', views.ListLoanProducts, name="get-loan-product"),
    path('profile', views.Profile, name="profile"),
    path('upload-clients', views.UploadBulkClientTemplate, name='upload-clients'),
    path('bulk-client-template', views.CreateExcelTemplate, name='bulk-client-template'),
    path('bulk-client-view', views.BulkClientUploadView, name='bulk-client-view'),
    path('create-loan-product', views.CreateLoanProduct, name='create-loan-product'),
    path('new-loan-product', views.NewLoanProduct, name='new-loan-product'),
    path('calcluate-loan', views.calculateLoanRepayment, name='calculate-loan'),
    path('client/<int:client_id>/verify/', views.verify_user, name='verify_user'),
    path('pending_loans/<int:client_id>/', views.ApproveLoan, name='pending_loans'),
    path('active_loans', views.ActiveClientListView, name='active_loans'),
    path('closed_loans', views.ClosedLoansView, name='closed_loans'),
    # path('rejected_loans', views.RejectedLoansView, name='rejected_loans'),
]
